eureka:
  instance:
    hostname: localhost
    client:
         register:
         with:
         eureka: False
         fetch:
         -registry:
         service-url:
             defaultZone: http//${eureka.instance.hostname}:${server.port}/eureka/
server:
    port: 8080
    spring:
        config:
             import : optional:configserver:http://localhost:8081


       server:
         port: 8090
       spring:
           apllication:


#    spring:
#       config:
#            import: optional:configserver:http://localhost:8888





